---
- name: "Install Nessus Agent"
  ansible.builtin.dnf:
    name: nessus-agent
    state: present

- name: "Start and enable Nessus Agent service"
  ansible.builtin.systemd:
    name: "nessus-agent"
    state: started
    enabled: true

- name: "Check if Nessus Agent is already linked"
  ansible.builtin.shell: "/opt/nessus_agent/sbin/nessuscli agent status; true"
  register: nessus_agent_link_status
  ignore_errors: true
  changed_when: false

- name: "Extract linked hostname"
  ansible.builtin.set_fact:
    nessus_linked_hostname: "{{ nessus_agent_link_status.stdout | regex_search('Linked to\\s+([\\w\\.-]+)', '\\1') }}"
  when: "'Linked to' in nessus_agent_link_status.stdout"

- name: "List linked hostname"
  ansible.builtin.debug:
    msg: "Nessus Agent is linked to: {{ nessus_linked_hostname }}"
  when: "'Linked to' in nessus_agent_link_status.stdout"

- name: "Link Nessus Agent to Nessus server"
  ansible.builtin.command: "/opt/nessus_agent/sbin/nessuscli agent link --key={{ nessus_agent_activation_code }} --groups={{ nessus_agent_groups }} --host={{ nessus_agent_nessus_server }} --port={{ nessus_agent_port }}"
  changed_when: true
  when: "'Linked to' not in nessus_agent_link_status.stdout or nessus_linked_hostname != nessus_agent_nessus_server or nessus_agent_force_link | default(false)"
  notify: "Restart Nessus Agent service"
