---
- name: "Install Nessus Agent"
  ansible.builtin.dnf:
    name: NessusAgent
    state: present

- name: "Start and enable Nessus Agent service"
  ansible.builtin.systemd:
    name: "nessusagent"
    state: started
    enabled: true
