---
- name: "Get Nessus Agent Status"
  ansible.builtin.shell: "/opt/nessus_agent/sbin/nessuscli agent status"
  ignore_errors: true
  changed_when: false
  register: nessus_agent_status

- name: "Set nessus_agent_linked"
  ansible.builtin.set_fact:
    nessus_agent_linked: "{{ nessus_agent_status.stdout | regex_search('Linked to:\\s+([\\w\\.-]+):\\d+') is not none }}"

- name: "Extract the hostname using regex"
  ansible.builtin.set_fact:
    nessus_agent_linked_hostname: "{{ nessus_agent_status.stdout | regex_search('(?<=Linked to: )([^\\s:]+)(?=:?)') }}"
  when: nessus_agent_status.stdout | regex_search('Linked to:\\s+([\\w\\.-]+):\\d+')

- name: "Display nessus_agent_linked"
  ansible.builtin.debug:
    msg: "Nessus Agent linked status: {{ nessus_agent_linked }}"

- name: "Display nessus_agent_linked_hostname"
  ansible.builtin.debug:
    msg: "Nessus Agent is linked to: {{ nessus_agent_linked_hostname }}"
  when: nessus_agent_linked_hostname | default(false)

- name: "Set if agent link is required"
  ansible.builtin.set_fact:
    nessus_agent_link_required: true
  when: not nessus_agent_linked or nessus_agent_force_link or (nessus_agent_linked_hostname is defined and nessus_agent_linked_hostname != nessus_agent_nessus_server)

- name: "Display if agent link is required"
  ansible.builtin.debug:
    msg: "Nessus Agent requires server link"
  when: nessus_agent_link_required | default(false)

- name: "Unlink Nessus Agent"
  ansible.builtin.command: "/opt/nessus_agent/sbin/nessuscli agent unlink"
  changed_when: true
  when: (nessus_agent_link_required | default(false) and nessus_agent_linked) or (nessus_agent_state == "absent" and nessus_agent_linked)

- name: "Link Nessus Agent"
  ansible.builtin.command: "/opt/nessus_agent/sbin/nessuscli agent link --key={{ nessus_agent_activation_code }} --groups={{ nessus_agent_groups }} --host={{ nessus_agent_nessus_server }} --port={{ nessus_agent_port }}"
  changed_when: true
  when: nessus_agent_link_required | default(false) and nessus_agent_state == "present"
  notify: "Restart Nessus Agent service"

- name: "Ensure /opt/nessus_agent/link_key exists"
  ansible.
