---
- name: "Remove Nessus Agent"
  ansible.builtin.dnf:
    name: NessusAgent
    state: absent

- name: "Remove /opt/nessus_agent"
  ansible.builtin.file:
    path: "/opt/nessus_agent"
    state: absent
